version: '3.8'
services:
  gateway:
    build: ./gateway
    image: share_it_gateway_image
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: share_it_server_image
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

  db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=shareit