version: '3.8'
services:
  gateway:
    image: gateway_image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    image: server_image
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
      - gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=shareit